# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: joker_guide.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'joker_guide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11joker_guide.proto\x12\x0ejoker_guide.v1\"\x1c\n\x0cResetRequest\x12\x0c\n\x04seed\x18\x01 \x01(\x04\"h\n\rResetResponse\x12\x30\n\x0bobservation\x18\x01 \x01(\x0b\x32\x1b.joker_guide.v1.Observation\x12%\n\x04info\x18\x02 \x01(\x0b\x32\x17.joker_guide.v1.EnvInfo\"5\n\x0bStepRequest\x12&\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x16.joker_guide.v1.Action\"\x85\x01\n\x0cStepResponse\x12\x30\n\x0bobservation\x18\x01 \x01(\x0b\x32\x1b.joker_guide.v1.Observation\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12%\n\x04info\x18\x04 \x01(\x0b\x32\x17.joker_guide.v1.EnvInfo\"\x10\n\x0eGetSpecRequest\"\x89\x01\n\x0fGetSpecResponse\x12/\n\x0bobservation\x18\x01 \x01(\x0b\x32\x1a.joker_guide.v1.TensorSpec\x12/\n\x0b\x61\x63tion_mask\x18\x02 \x01(\x0b\x32\x1a.joker_guide.v1.TensorSpec\x12\x14\n\x0c\x61\x63tion_space\x18\x03 \x01(\x05\"d\n\x0bObservation\x12(\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32\x16.joker_guide.v1.Tensor\x12+\n\x0b\x61\x63tion_mask\x18\x02 \x01(\x0b\x32\x16.joker_guide.v1.Tensor\"%\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"*\n\nTensorSpec\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\t\"@\n\x06\x41\x63tion\x12\x11\n\taction_id\x18\x01 \x01(\x05\x12\x0e\n\x06params\x18\x02 \x03(\x05\x12\x13\n\x0b\x61\x63tion_type\x18\x03 \x01(\x05\"R\n\x07\x45nvInfo\x12\x14\n\x0c\x65pisode_step\x18\x01 \x01(\x05\x12\r\n\x05\x63hips\x18\x02 \x01(\x03\x12\x0c\n\x04mult\x18\x03 \x01(\x03\x12\x14\n\x0c\x62lind_target\x18\x04 \x01(\x03\x32\xdf\x01\n\x08JokerEnv\x12\x44\n\x05Reset\x12\x1c.joker_guide.v1.ResetRequest\x1a\x1d.joker_guide.v1.ResetResponse\x12\x41\n\x04Step\x12\x1b.joker_guide.v1.StepRequest\x1a\x1c.joker_guide.v1.StepResponse\x12J\n\x07GetSpec\x12\x1e.joker_guide.v1.GetSpecRequest\x1a\x1f.joker_guide.v1.GetSpecResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'joker_guide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESETREQUEST']._serialized_start=37
  _globals['_RESETREQUEST']._serialized_end=65
  _globals['_RESETRESPONSE']._serialized_start=67
  _globals['_RESETRESPONSE']._serialized_end=171
  _globals['_STEPREQUEST']._serialized_start=173
  _globals['_STEPREQUEST']._serialized_end=226
  _globals['_STEPRESPONSE']._serialized_start=229
  _globals['_STEPRESPONSE']._serialized_end=362
  _globals['_GETSPECREQUEST']._serialized_start=364
  _globals['_GETSPECREQUEST']._serialized_end=380
  _globals['_GETSPECRESPONSE']._serialized_start=383
  _globals['_GETSPECRESPONSE']._serialized_end=520
  _globals['_OBSERVATION']._serialized_start=522
  _globals['_OBSERVATION']._serialized_end=622
  _globals['_TENSOR']._serialized_start=624
  _globals['_TENSOR']._serialized_end=661
  _globals['_TENSORSPEC']._serialized_start=663
  _globals['_TENSORSPEC']._serialized_end=705
  _globals['_ACTION']._serialized_start=707
  _globals['_ACTION']._serialized_end=771
  _globals['_ENVINFO']._serialized_start=773
  _globals['_ENVINFO']._serialized_end=855
  _globals['_JOKERENV']._serialized_start=858
  _globals['_JOKERENV']._serialized_end=1081
# @@protoc_insertion_point(module_scope)
